language: python

services:
  - docker

before_install:
  - curl -o docker-compose.yml https://raw.githubusercontent.com/FusionAuth/fusionauth-containers/master/docker/fusionauth/docker-compose.yml
  - curl -o .env https://raw.githubusercontent.com/FusionAuth/fusionauth-containers/master/docker/fusionauth/.env
  - docker pull postgres:11.9-alpine
  - docker pull fusionauth/fusionauth-app:latest
  - docker-compose up -d
  - sleep 18

script:
  - bash tests/tests.sh
  - docker ps -a
  - sleep 10
  - docker-compose logs



after_success:
  - docker-compose down


after_failure:
  - docker-compose down
