language: python

services:
  - docker

before_install:
  - ## Get the default files
  - curl -o docker-compose.yml https://raw.githubusercontent.com/FusionAuth/fusionauth-containers/master/docker/fusionauth/docker-compose.yml
  - curl -o .env https://raw.githubusercontent.com/FusionAuth/fusionauth-containers/master/docker/fusionauth/.env
  - ## Set the needed Environment variables
  - export DISCOVERY_URL=http://localhost:9011/.well-known/openid-configuration
  - export FUSIONAUTH_API_KEY=4737ea8520bd454caabb7cb3d36e14bc1832c0d3f70a4189b82598670f11b1bd
  - export FUSIONAUTH_APP_KICKSTART_FILE=/usr/local/fusionauth/kickstart/device_code-grant_require_authentication_false.json
  - export APPLICATION_ID=89d998a5-aaef-45d0-9765-adf1f3e00c65
  - export DEF_TENANTID=d7d09513-a3f5-401c-9685-34ab6c552453
  - export APP_USEREMAIL=user@local.nu
  - export APP_USERPASSWORD=userpassword
  - ## Move the docker-compose override
  - mv ./tests/docker-compose.override.yml ./docker-compose.override.yml
  - docker-compose up -d
  - ## Show the running config
  - docker-compose config
  - ## Make sure Fusionauth is started up completely
  - sleep 45

script:
  - ## Run the test script
  - bash tests/tests.sh



after_success:
  - docker-compose down


after_failure:
  - docker-compose down
