language: python

services:
  - docker

before_install:
  - sudo apt-get install jq -y
  - curl -o docker-compose.yml https://raw.githubusercontent.com/FusionAuth/fusionauth-containers/master/docker/fusionauth/docker-compose.yml
  - curl -o .env https://raw.githubusercontent.com/FusionAuth/fusionauth-containers/master/docker/fusionauth/.env
  - docker pull postgres:11.9-alpine
  - docker pull fusionauth/fusionauth-app:latest
  - echo "">>.env
  - export FUSIONAUTH_API_KEY=4737ea8520bd454caabb7cb3d36e14bc1832c0d3f70a4189b82598670f11b1bd
  - export FUSIONAUTH_APP_KICKSTART_FILE=/usr/local/fusionauth/kickstart/kickstart.json
  - export APPLICATION_ID=89d998a5-aaef-45d0-9765-adf1f3e00c65
  - echo "Populating .env"
  - echo "FUSIONAUTH_APP_KICKSTART_FILE=$FUSIONAUTH_APP_KICKSTART_FILE">>.env
  - echo "FUSIONAUTH_API_KEY=$FUSIONAUTH_API_KEY">>.env
  - echo "APPLICATION_ID=$APPLICATION_ID">>.env
  - mv ./tests/docker-compose.override.yml ./docker-compose.override.yml
  - docker-compose up -d
  - docker-compose config
  - sleep 45

script:
  - bash tests/tests.sh
  - docker ps -a



after_success:
  - docker-compose down


after_failure:
  - docker-compose down
