language: python

services:
  - docker

before_install:
  - curl -o docker-compose.yml https://raw.githubusercontent.com/FusionAuth/fusionauth-containers/master/docker/fusionauth/docker-compose.yml
  - curl -o .env https://raw.githubusercontent.com/FusionAuth/fusionauth-containers/master/docker/fusionauth/.env
  - docker pull postgres:11.9-alpine
  - docker pull fusionauth/fusionauth-app:latest
  - echo "">>.env
  - echo "FUSIONAUTH_APP_KICKSTART_FILE=/usr/local/fusionauth/kickstart/kickstart.json">>.env
  - echo "FUSIONAUTH_API_KEY=4737ea8520bd454caabb7cb3d36e14bc1832c0d3f70a4189b82598670f11b1bd">>.env
  - docker-compose up -d
  - sleep 45

script:
  - docker logs fusionauth
  - bash tests/tests.sh
  - docker ps -a
  - sleep 10
  - docker logs fusionauth



after_success:
  - docker-compose down


after_failure:
  - docker-compose down
