version: '3'

services:
  fusionauth:
    container_name: fusionauth
    environment:
      - FUSIONAUTH_APP_KICKSTART_FILE=/usr/local/fusionauth/kickstart/kickstart.json
      - FUSIONAUTH_ADMIN_PASSWORD=supersecret
      - FUSIONAUTH_API_KEY=4737ea8520bd454caabb7cb3d36e14bc1832c0d3f70a4189b82598670f11b1bd
      - DEF_TENANTID=d7d09513-a3f5-401c-9685-34ab6c552453
      - APPLICATION_ID=89d998a5-aaef-45d0-9765-adf1f3e00c65
      - APP_USEREMAIL=user@local.nu
      - APP_USERPASSWORD=userpassword

    volumes:
      - ./tests/kickstart:/usr/local/fusionauth/kickstart
      - fa_config:/usr/local/fusionauth/config
